version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+mysqlconnector://fv_g4_admin:Bd2025!@mysql.reto-ucu.net:50006/FV_Grupo4
      - SECRET_KEY=clavesecreta1
      - DB_HOST=mysql.reto-ucu.net
      - DB_PORT=50006
      - DB_USER=fv_g4_admin
      - DB_PASSWORD=Bd2025!
      - DB_NAME=FV_Grupo4